# Generated by Django 3.2.8 on 2022-08-20 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='compiled',
        ),
    ]
