#include "lookup_x86_64_linux.h"

const char *data_section_x86_64_linux =
    "    .section .data\n"
    "buf:\n"
    "    .fill 100\n"
    "int_buf:\n"
    "    .fill 100\n"
    "stack:\n"
    "    .fill 800\n"
    "stack_ptr:\n"
    "    .quad 0\n"
    "strlen:\n"
    "    .quad 0\n"
    "seed:\n"
    "    .quad 0";

const char *text_start_x86_64_linux_0 =
    "    .section .text\n"
    "    .globl _start\n"
    "calc_strlen:\n"
    "    movq stack_ptr, %rax\n"
    "    subq $8, %rax\n"
    "    movq (%rax), %rbx\n"
    "    movabsq $0, %rcx\n"
    "calc_strlen_loop0:\n"
    "    movb (%rbx), %r10b\n"
    "    cmpb $0, %r10b\n"
    "    je calc_strlen_end_loop0\n"
    "    addq $1, %rbx\n"
    "    addq $1, %rcx\n"
    "    jmp calc_strlen_loop0\n"
    "calc_strlen_end_loop0:\n"
    "    movq %rcx, strlen\n"
    "    ret\n"
    "print_str:\n"
    "    movabsq $1, %rdi\n"
    "    movq stack_ptr, %rax\n"
    "    subq $8, %rax\n"
    "    movq %rax, stack_ptr\n"
    "    movq (%rax), %rsi\n"
    "    movq strlen, %rdx\n"
    "    movabsq $1, %rax\n"
    "    syscall\n"
    "    ret\n"
    "print_chr:\n"
    "    movabsq $1, %rdi\n"
    "    movq stack_ptr, %rax\n"
    "    subq $8, %rax\n"
    "    movq %rax, stack_ptr\n"
    "    movb (%rax), %bl\n"
    "    movb %bl, buf\n"
    "    movabsq $buf, %rsi\n"
    "    movabsq $1, %rdx\n"
    "    movabsq $1, %rax\n"
    "    syscall\n"
    "    ret\n"
    "println_str:\n"
    "    movabsq $1, %rdi\n"
    "    movq stack_ptr, %rax\n"
    "    subq $8, %rax\n"
    "    movq %rax, stack_ptr\n"
    "    movq (%rax), %rsi\n"
    "    movq strlen, %rdx\n"
    "    movabsq $1, %rax\n"
    "    syscall\n"
    "    movabsq $1, %rdi\n"
    "    movabsq $buf, %rsi\n"
    "    movb $10, buf\n"
    "    movabsq $1, %rdx\n"
    "    movabsq $1, %rax\n"
    "    syscall\n"
    "    ret\n"
    "println_chr:\n"
    "    movabsq $1, %rdi\n"
    "    movq stack_ptr, %rax\n"
    "    subq $8, %rax\n"
    "    movq %rax, stack_ptr\n"
    "    movb (%rax), %bl\n"
    "    movb %bl, buf\n"
    "    movabsq $buf, %rsi\n"
    "    movabsq $1, %rdx\n"
    "    movabsq $1, %rax\n"
    "    syscall\n"
    "    movabsq $1, %rdi\n"
    "    movabsq $buf, %rsi\n"
    "    movb $10, buf\n"
    "    movabsq $1, %rdx\n"
    "    movabsq $1, %rax\n"
    "    syscall\n"
    "    ret\n"
    "print_int:\n"
    "    movabsq $1, %rdi\n"
    "    movq stack_ptr, %rax\n"
    "    subq $8, %rax\n"
    "    movq %rax, stack_ptr\n"
    "    movq (%rax), %rax\n"
    "    movabsq $0, %rdx\n"
    "    movq %rax, %r15\n"
    "    movq $0, %r10\n"
    "    cmpq %r10, %r15\n"
    "    jge print_int_eif0\n"
    "    negq %rax\n"
    "print_int_eif0:\n"
    "    movabsq $int_buf, %r10\n"
    "    movabsq $0, %r11\n"
    "    movabsq $0, %r12\n"
    "    movabsq $10, %rbx\n"
    "print_int_loop0:\n"
    "    divq %rbx\n"
    "    addq $48, %rdx\n"
    "    movb %dl, (%r10)\n"
    "    movabsq $0, %rdx\n"
    "    addq $1, %r10\n"
    "    addq $1, %r11\n"
    "    cmpq %rax, %r12\n"
    "    jne print_int_loop0\n"
    "    movabsq $buf, %r12\n"
    "    movabsq $0, %r14\n"
    "    cmpq %r14, %r15\n"
    "    jge print_int_eif1\n"
    "    movb $45, (%r12)\n"
    "    addq $1, %r12\n"
    "    addq $1, %r11\n"
    "print_int_eif1:\n"
    "    movq %r11, strlen\n"
    "print_int_loop1:\n"
    "    subq $1, %r10\n"
    "    movb (%r10), %r13b\n"
    "    movb %r13b, (%r12)\n"
    "    addq $1, %r12\n"
    "    subq $1, %r11\n"
    "    cmpq %r11, %r14\n"
    "    jne print_int_loop1\n"
    "    movabsq $buf, %rsi\n"
    "    movq strlen, %rdx\n"
    "    movabsq $1, %rax\n"
    "    syscall\n"
    "    ret\n"
    "println_int:\n"
    "    movabsq $1, %rdi\n"
    "    movq stack_ptr, %rax\n"
    "    subq $8, %rax\n"
    "    movq %rax, stack_ptr\n"
    "    movq (%rax), %rax\n"
    "    movabsq $0, %rdx\n"
    "    movq %rax, %r15\n"
    "    movq $0, %r10\n"
    "    cmpq %r10, %r15\n"
    "    jge println_int_eif0\n"
    "    negq %rax\n"
    "println_int_eif0:\n"
    "    movabsq $int_buf, %r10\n"
    "    movabsq $0, %r11\n"
    "    movabsq $0, %r12\n"
    "    movabsq $10, %rbx\n"
    "println_int_loop0:\n"
    "    divq %rbx\n"
    "    addq $48, %rdx\n"
    "    movb %dl, (%r10)\n"
    "    movabsq $0, %rdx\n"
    "    addq $1, %r10\n"
    "    addq $1, %r11\n"
    "    cmpq %rax, %r12\n"
    "    jne println_int_loop0\n"
    "    movabsq $buf, %r12\n"
    "    movabsq $0, %r14\n"
    "    cmpq %r14, %r15\n"
    "    jge println_int_eif1\n"
    "    movb $45, (%r12)\n"
    "    addq $1, %r12\n"
    "    addq $1, %r11\n"
    "println_int_eif1:\n"
    "    movq %r11, strlen\n"
    "println_int_loop1:\n"
    "    subq $1, %r10\n"
    "    movb (%r10), %r13b\n"
    "    movb %r13b, (%r12)\n"
    "    addq $1, %r12\n"
    "    subq $1, %r11\n"
    "    cmpq %r11, %r14\n"
    "    jne println_int_loop1\n"
    "    movabsq $buf, %rsi\n"
    "    movq strlen, %rdx\n"
    "    movabsq $1, %rax\n"
    "    syscall\n"
    "    movabsq $1, %rdi\n"
    "    movabsq $buf, %rsi\n"
    "    movb $10, buf\n"
    "    movabsq $1, %rdx\n"
    "    movabsq $1, %rax\n"
    "    syscall\n"
    "    ret";

const char *text_start_x86_64_linux_1 =
    "input:\n"
    "    movq stack_ptr, %r10\n"
    "    subq $8, %r10\n"
    "    movabsq $0, %rax\n"
    "    movabsq $0, %rdi\n"
    "    movabsq $buf, %rsi\n"
    "    movabsq $1, %rdx\n"
    "    syscall\n"
    "    movabsq $0, %r15\n"
    "    movabsq $0, %r11\n"
    "    movb (%rsi), %r11b\n"
    "    movabsq $48, %r13\n"
    "    movabsq $0, %r12\n"
    "    cmpb $45, %r11b\n"
    "    jne input_else0\n"
    "    movabsq $1, %r15\n"
    "    jmp input_eif0\n"
    "input_else0:\n"
    "    cmpb $48, %r11b\n"
    "    cmovlq %r13, %r11\n"
    "    cmpb $57, %r11b\n"
    "    cmovgq %r13, %r11\n"
    "    subq $48, %r11\n"
    "    addq %r11, %r12\n"
    "input_eif0:\n"
    "    movq $10, %r14\n"
    "input_loop0:\n"
    "    movq $0, %rax\n"
    "    movq $1, %rdx\n"
    "    syscall\n"
    "    movabsq $0, %r11\n"
    "    movb (%rsi), %r11b\n"
    "    cmpb $10, %r11b\n"
    "    je input_end_loop0\n"
    "    movq %r12, %rax\n"
    "    cqo\n"
    "    imulq %r14\n"
    "    movq %rax, %r12\n"
    "    cmpb $48, %r11b\n"
    "    cmovlq %r13, %r11\n"
    "    cmpb $57, %r11b\n"
    "    cmovgq %r13, %r11\n"
    "    subq $48, %r11\n"
    "    addq %r11, %r12\n"
    "    jmp input_loop0\n"
    "input_end_loop0:\n"
    "    cmpb $0, %r15b\n"
    "    je input_eif1\n"
    "    negq %r12\n"
    "input_eif1:\n"
    "    movq (%r10), %r15\n"
    "    movq %r12, (%r15)\n"
    "    movq %r10, stack_ptr\n"
    "    ret\n"
    "srand:\n"
    "    movq stack_ptr, %rax\n"
    "    subq $8, %rax\n"
    "    movq %rax, stack_ptr\n"
    "    movq (%rax), %rax\n"
    "    movq %rax, seed\n"
    "    ret\n"
    "rand:\n"
    "    movq seed, %rax\n"
    "    movabsq $2862933555777941757, %rbx\n"
    "    movq $0, %rdx\n"
    "    mulq %rbx\n"
    "    movabsq $3037000493, %rbx\n"
    "    addq %rbx, %rax\n"
    "    movabsq $0x7fffffffffffffff, %rbx\n"
    "    andq %rbx, %rax\n"
    "    movq stack_ptr, %r10\n"
    "    movq %rax, (%r10)\n"
    "    addq $8, %r10\n"
    "    movq %r10, stack_ptr\n"
    "    movq %rax, seed\n"
    "    ret";

const char *program_start_x86_64_linux =
    "_start:\n"
    "    movabsq $stack, %rax\n"
    "    movq %rax, stack_ptr";

const char *text_end_x86_64_linux =
    "    movq $60, %rax\n"
    "    movq $0, %rdi\n"
    "    syscall";
