#include "errcodes.h"

const char *errcode_lookup[16] = {
    "ERR_OK",
    "ERR_NULL_PTR",
    "ERR_OUT_OF_MEMORY",
    "ERR_FILE_IO",
    "ERR_INVALID_VAR_NAME",
    "ERR_INVALID_STR_LIT",
    "ERR_INVALID_OPERATOR",
    "ERR_ARR_NOT_INITIALIZED",
    "ERR_INVALID_INT_LIT",
    "ERR_INVALID_ARR_SIZE",
    "ERR_INVALID_COMMAND",
    "ERR_EMPTY_DARRAY",
    "ERR_UNBALANCED_ELSE",
    "ERR_UNBALANCED_END",
    "ERR_STACK_OVERFLOW",
    "ERR_INVALID_OPERAND"
};
