#include "lookup_arm64_linux.h"

const char *data_section_arm64_linux =
    "    .data\n"
    "str_buf:\n"
    "    .fill 100\n"
    "int_buf:\n"
    "    .fill 100\n"
    "stack:\n"
    "    .fill 800\n"
    "stack_ptr:\n"
    "    .quad 0\n"
    "strlen:\n"
    "    .quad 0\n"
    "seed:\n"
    "    .quad 0";

const char *text_start_arm64_linux_0 =
    "    .text\n"
    "    .global _start\n"
    "calc_strlen:\n"
    "    ldr x9, =stack_ptr\n"
    "    ldr x10, [x9]\n"
    "    sub x10, x10, #8\n"
    "    ldr x11, [x10]\n"
    "    mov x12, #0\n"
    "calc_strlen_loop0:\n"
    "    ldrb w13, [x11]\n"
    "    cmp x13, #0\n"
    "    beq calc_strlen_end_loop0\n"
    "    add x11, x11, 1\n"
    "    add x12, x12, 1\n"
    "    b calc_strlen_loop0\n"
    "calc_strlen_end_loop0:\n"
    "    ldr x9, =strlen\n"
    "    str x12, [x9]\n"
    "    ret\n"
    "print_str:\n"
    "    ldr x9, =stack_ptr\n"
    "    ldr x10, [x9]\n"
    "    sub x10, x10, #8\n"
    "    str x10, [x9]\n"
    "    ldr x11, [x10]\n"
    "    mov x8, #64\n"
    "    mov x0, #1\n"
    "    mov x1, x11\n"
    "    ldr x9, =strlen\n"
    "    ldr x10, [x9]\n"
    "    mov x2, x10\n"
    "    svc #0\n"
    "    ret\n"
    "println_str:\n"
    "    ldr x9, =stack_ptr\n"
    "    ldr x10, [x9]\n"
    "    sub x10, x10, #8\n"
    "    str x10, [x9]\n"
    "    ldr x11, [x10]\n"
    "    mov x8, #64\n"
    "    mov x0, #1\n"
    "    mov x1, x11\n"
    "    ldr x9, =strlen\n"
    "    ldr x10, [x9]\n"
    "    mov x2, x10\n"
    "    svc #0\n"
    "    ldr x9, =str_buf\n"
    "    mov x10, #10\n"
    "    strb w10, [x9]\n"
    "    mov x8, #64\n"
    "    mov x0, #1\n"
    "    mov x1, x9\n"
    "    mov x2, #1\n"
    "    svc #0\n"
    "    ret\n"
    "print_chr:\n"
    "    ldr x9, =stack_ptr\n"
    "    ldr x10, [x9]\n"
    "    sub x10, x10, #8\n"
    "    str x10, [x9]\n"
    "    ldr x11, [x10]\n"
    "    ldr x12, =str_buf\n"
    "    strb w11, [x12]\n"
    "    mov x8, #64\n"
    "    mov x0, #1\n"
    "    mov x1, x12\n"
    "    mov x2, #1\n"
    "    svc #0\n"
    "    ret\n"
    "println_chr:\n"
    "    ldr x9, =stack_ptr\n"
    "    ldr x10, [x9]\n"
    "    sub x10, x10, #8\n"
    "    str x10, [x9]\n"
    "    ldr x11, [x10]\n"
    "    ldr x12, =str_buf\n"
    "    strb w11, [x12]\n"
    "    mov x8, #64\n"
    "    mov x0, #1\n"
    "    mov x1, x12\n"
    "    mov x2, #1\n"
    "    svc #0\n"
    "    ldr x9, =str_buf\n"
    "    mov x10, #10\n"
    "    strb w10, [x9]\n"
    "    mov x8, #64\n"
    "    mov x0, #1\n"
    "    mov x1, x9\n"
    "    mov x2, #1\n"
    "    svc #0\n"
    "    ret";

const char *text_start_arm64_linux_1 =
    "print_int:\n"
    "    ldr x9, =stack_ptr\n"
    "    ldr x10, [x9]\n"
    "    sub x10, x10, #8\n"
    "    str x10, [x9]\n"
    "    ldr x11, [x10]\n"
    "    mov x20, #0\n"
    "    cmp x11, #0\n"
    "    bge print_int_eif0\n"
    "    mov x20, #1\n"
    "    neg x11, x11\n"
    "print_int_eif0:\n"
    "    mov x12, #0\n"
    "    ldr x13, =int_buf\n"
    "print_int_loop0:\n"
    "    mov x14, #10\n"
    "    udiv x15, x11, x14\n"
    "    msub x16, x15, x14, x11\n"
    "    add x16, x16, #48\n"
    "    strb w16, [x13]\n"
    "    mov x11, x15\n"
    "    add x12, x12, #1\n"
    "    add x13, x13, #1\n"
    "    cmp x11, #0\n"
    "    bgt print_int_loop0\n"
    "    mov x21, x12\n"
    "    sub x13, x13, 1\n"
    "    ldr x14, =str_buf\n"
    "    cmp x20, #0\n"
    "    beq print_int_eif1\n"
    "    mov x15, #45\n"
    "    strb w15, [x14]\n"
    "    add x14, x14, 1\n"
    "print_int_eif1:\n"
    "print_int_loop1:\n"
    "    ldrb w15, [x13]\n"
    "    strb w15, [x14]\n"
    "    sub x12, x12, #1\n"
    "    sub x13, x13, #1\n"
    "    add x14, x14, #1\n"
    "    cmp x12, #0\n"
    "    bgt print_int_loop1\n"
    "    mov x8, #64\n"
    "    mov x0, #1\n"
    "    ldr x1, =str_buf\n"
    "    mov x2, x21\n"
    "    cmp x20, #0\n"
    "    beq print_int_eif2\n"
    "    add x2, x2, 1\n"
    "print_int_eif2:\n"
    "    svc #10\n"
    "    ret\n"
    "println_int:\n"
    "    ldr x9, =stack_ptr\n"
    "    ldr x10, [x9]\n"
    "    sub x10, x10, #8\n"
    "    str x10, [x9]\n"
    "    ldr x11, [x10]\n"
    "    mov x20, #0\n"
    "    cmp x11, #0\n"
    "    bge println_int_eif0\n"
    "    mov x20, #1\n"
    "    neg x11, x11\n"
    "println_int_eif0:\n"
    "    mov x12, #0\n"
    "    ldr x13, =int_buf\n"
    "println_int_loop0:\n"
    "    mov x14, #10\n"
    "    udiv x15, x11, x14\n"
    "    msub x16, x15, x14, x11\n"
    "    add x16, x16, #48\n"
    "    strb w16, [x13]\n"
    "    mov x11, x15\n"
    "    add x12, x12, #1\n"
    "    add x13, x13, #1\n"
    "    cmp x11, #0\n"
    "    bgt println_int_loop0\n"
    "    mov x21, x12\n"
    "    sub x13, x13, 1\n"
    "    ldr x14, =str_buf\n"
    "    cmp x20, #0\n"
    "    beq println_int_eif1\n"
    "    mov x15, #45\n"
    "    strb w15, [x14]\n"
    "    add x14, x14, 1\n"
    "println_int_eif1:\n"
    "println_int_loop1:\n"
    "    ldrb w15, [x13]\n"
    "    strb w15, [x14]\n"
    "    sub x12, x12, #1\n"
    "    sub x13, x13, #1\n"
    "    add x14, x14, #1\n"
    "    cmp x12, #0\n"
    "    bgt println_int_loop1\n"
    "    mov x8, #64\n"
    "    mov x0, #1\n"
    "    ldr x1, =str_buf\n"
    "    mov x2, x21\n"
    "    cmp x20, #0\n"
    "    beq println_int_eif2\n"
    "    add x2, x2, 1\n"
    "println_int_eif2:\n"
    "    svc #10\n"
    "    ldr x9, =str_buf\n"
    "    mov x10, #10\n"
    "    strb w10, [x9]\n"
    "    mov x8, #64\n"
    "    mov x0, #1\n"
    "    mov x1, x9\n"
    "    mov x2, #1\n"
    "    svc #0\n"
    "    ret";

const char *program_start_arm64_linux =
    "_start:\n"
    "    ldr x9, =stack\n"
    "    ldr x10, =stack_ptr\n"
    "    str x9, [x10]";

const char *text_end_arm64_linux =
    "    mov x8, #93\n"
    "    mov x0, #0\n"
    "    svc #0";
